version: "3"

services:

  # webserver
  nginx:
    build:
      dockerfile: docker/dockerfiles/nginx/Dockerfile
    container_name: 'demo777-nginx'
    ports:
      - "8077:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - demo777

  # php
  php-fpm:
    build:
      dockerfile: docker/dockerfiles/php/Dockerfile
    container_name: 'demo777-php'
    volumes:
      - ./src:/var/www/html
    networks:
      - demo777

networks:
  demo777:
    driver: bridge
