version: "3"

services:

  # webserver
  nginx:
    build:
      dockerfile: dockerfiles/nginx/Dockerfile
    container_name:  '${COMPOSE_PROJECT_NAME}-nginx'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - ../src/:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - custom_network_identifier

  # php
  php-fpm:
    build:
      dockerfile: dockerfiles/php/Dockerfile
    container_name:  '${COMPOSE_PROJECT_NAME}-php'
    volumes:
      - ../src/:/var/www/html
    networks:
      - custom_network_identifier

networks:
  custom_network_identifier:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge
